### ISSUE TITLE
Replace with an index of locallized examples

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/examples#81]
Many examples in this repo are out of date and no longer work with newer versions of our SDKs.

Our long-term plan is to have examples co-located with their SDKs, which we are already moving towards.

Remove examples from this repo, and either move them if they work, or add an issue to add such a working example in the appropriate SDK repo.

Add an index in this repo pointing to each examples directory in our SDK repos.

[Sync topic](https://honeycomb.quip.com/o7fLAOAQ80cu/Telemetry-Team-Sync#temp:C:GFGbd80bd84223c49a2a300c2798): suggest SA team to add their examples to the index

- [x] dotnet-core-webapi
- [x] dotnet-otlp
- [x] golang-gatekeeper
- [x] golang-otlp
- [x] golang-ratelimiting-proxy
- [x] golang-webapp
- [x] golang-wiki-tracing
- [x] honeytail-haproxy
- [x] honeytail-mysql
- [x] honeytail-nginx
- [x] honeytail-dockerd
- [x] java-beeline
- [x] java-otlp
- [x] java-webapp
- [x] kubernetes-envoy-tracing
- [x] node-otlp
- [x] node-serverless-app
- [x] node-tracing-example
- [x] python-api
- [x] python-gatekeeper
- [x] python-otlp
- [x] ruby-gatekeeper
- [x] ruby-otlp
- [x] tuby-wiki-tracing
- [x] webhook-listener-triggers
- [x] clean up README, explain that it's a reference repo

**Comment by MikeGoldsmith** [comment]
Any examples removed from the repo need to have links in docs repo removed / updated.
